version: '3'
services:
  speech_to_text:
    image: inviewteam/sst
    container_name: sst
    environment:
      ASSISTANT_HOST: http://25.49.45.18
      ASSISTANT_PORT: 30003
      SERVICE_MODE: gpu
    volumes:
      - ./cache:/app/cache
    ports:
      - "30001:30001"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]