openapi: 3.0.0
info:
  title: Speech-To-Text API
  description: Service for convert voice to text
  version: '1.0.0'
servers:
  - url: http://127.0.0.1:{port}/{basePath}/v{version}
    description: Localhost
    variables:
      port:
        default: "30001"
      basePath:
        default: "api"
      version:
        default: "1"
paths:
  /commands:
    post:
      description: Convert voice to text
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
        - in: header
          name: Session-ID
          schema:
            type: string
      responses:
        "200":
          description: "Successful Response"
        "422":
          description: "Unprocessable Entity"
        
        